name: gpdb_local

releases:
  - name: database
    version: latest

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: master
    instances: 1
    persistent_disk: 2_048
    vm_type: small
    jobs:
      - name: master
        release: database
    azs:
      - z1
    networks:
      - name: internal
    stemcell: default

  - name: segment
    instances: 1
    persistent_disk: 8_192
    vm_type: medium
    jobs:
      - name: segment
        release: database
    azs:
      - z1
    networks:
      - name: internal
    stemcell: default

update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  serial: false

director_uuid: 2db63f0d-b544-456a-b923-86c1e689fcc9
